import spacy
from pathlib import Path

print("Chargement du modele NER...")
nlp = spacy.load("models_v2/ner_model_spacy/model-best")

ruler = nlp.add_pipe("entity_ruler", before="ner", config={"overwrite_ents": False})

patterns = [
    # ── ANIMAL ───────────────────────────────────────────────────
    {"label": "ANIMAL", "pattern": "budgie"},
    {"label": "ANIMAL", "pattern": "budgerigar"},
    {"label": "ANIMAL", "pattern": "cockatiel"},
    {"label": "ANIMAL", "pattern": "cockatoo"},
    {"label": "ANIMAL", "pattern": "macaw"},
    {"label": "ANIMAL", "pattern": "lovebird"},
    {"label": "ANIMAL", "pattern": "finch"},
    {"label": "ANIMAL", "pattern": "tabby"},
    {"label": "ANIMAL", "pattern": "tabby cat"},
    {"label": "ANIMAL", "pattern": "golden retriever"},
    {"label": "ANIMAL", "pattern": "yorkshire terrier"},
    {"label": "ANIMAL", "pattern": "yorkshire"},
    {"label": "ANIMAL", "pattern": "jack russell"},
    {"label": "ANIMAL", "pattern": "border collie"},
    {"label": "ANIMAL", "pattern": "german shepherd"},
    {"label": "ANIMAL", "pattern": "cocker spaniel"},
    {"label": "ANIMAL", "pattern": "bearded dragon"},
    {"label": "ANIMAL", "pattern": "guinea pig"},
    {"label": "ANIMAL", "pattern": "gerbil"},
    {"label": "ANIMAL", "pattern": "chinchilla"},
    {"label": "ANIMAL", "pattern": "hedgehog"},
    {"label": "ANIMAL", "pattern": "tortoise"},
    {"label": "ANIMAL", "pattern": "goldfish"},
    {"label": "ANIMAL", "pattern": "betta"},
    {"label": "ANIMAL", "pattern": "persian"},
    {"label": "ANIMAL", "pattern": "persian cat"},
    {"label": "ANIMAL", "pattern": "siamese"},
    {"label": "ANIMAL", "pattern": "maine coon"},
    {"label": "ANIMAL", "pattern": "ragdoll"},
    {"label": "ANIMAL", "pattern": "bengal"},
    {"label": "ANIMAL", "pattern": "beagle"},
    {"label": "ANIMAL", "pattern": "pug"},
    {"label": "ANIMAL", "pattern": "dachshund"},
    {"label": "ANIMAL", "pattern": "corgi"},
    {"label": "ANIMAL", "pattern": "rottweiler"},
    {"label": "ANIMAL", "pattern": "doberman"},
    {"label": "ANIMAL", "pattern": "hamster"},
    {"label": "ANIMAL", "pattern": "donkey"},
    {"label": "ANIMAL", "pattern": "sheep"},
    {"label": "ANIMAL", "pattern": "goat"},
    {"label": "ANIMAL", "pattern": "duck"},
    {"label": "ANIMAL", "pattern": "chicken"},

    # ── SYMPTOM ──────────────────────────────────────────────────
    {"label": "SYMPTOM", "pattern": "refuses to drink"},
    {"label": "SYMPTOM", "pattern": "refuses to eat"},
    {"label": "SYMPTOM", "pattern": "refusing food"},
    {"label": "SYMPTOM", "pattern": "not eating"},
    {"label": "SYMPTOM", "pattern": "not drinking"},
    {"label": "SYMPTOM", "pattern": "cannot fly"},
    {"label": "SYMPTOM", "pattern": "can't fly"},
    {"label": "SYMPTOM", "pattern": "fell from"},
    {"label": "SYMPTOM", "pattern": "fell off"},
    {"label": "SYMPTOM", "pattern": "very weak"},
    {"label": "SYMPTOM", "pattern": "seems weak"},
    {"label": "SYMPTOM", "pattern": "looks weak"},
    {"label": "SYMPTOM", "pattern": "confused"},
    {"label": "SYMPTOM", "pattern": "disoriented"},
    {"label": "SYMPTOM", "pattern": "breathing fast"},
    {"label": "SYMPTOM", "pattern": "breathing rapidly"},
    {"label": "SYMPTOM", "pattern": "rapid breathing"},
    {"label": "SYMPTOM", "pattern": "heavy breathing"},
    {"label": "SYMPTOM", "pattern": "open mouth breathing"},
    {"label": "SYMPTOM", "pattern": "pale"},
    {"label": "SYMPTOM", "pattern": "looks pale"},
    {"label": "SYMPTOM", "pattern": "stopped eating"},
    {"label": "SYMPTOM", "pattern": "not active"},
    {"label": "SYMPTOM", "pattern": "not playful"},
    {"label": "SYMPTOM", "pattern": "lethargic"},
    {"label": "SYMPTOM", "pattern": "head tilt"},
    {"label": "SYMPTOM", "pattern": "circling"},
    {"label": "SYMPTOM", "pattern": "wobbly"},
    {"label": "SYMPTOM", "pattern": "limping badly"},
    {"label": "SYMPTOM", "pattern": "dragging leg"},
    {"label": "SYMPTOM", "pattern": "not bearing weight"},
    {"label": "SYMPTOM", "pattern": "loss of appetite"},
    {"label": "SYMPTOM", "pattern": "shortness of breath"},

    # ── DUREE — patterns PRECIS uniquement ───────────────────────
    # (suppression de : recently, suddenly, just, just now, all of a sudden)
    {"label": "DUREE", "pattern": "since yesterday"},
    {"label": "DUREE", "pattern": "since last night"},
    {"label": "DUREE", "pattern": "since this morning"},
    {"label": "DUREE", "pattern": "since this afternoon"},
    {"label": "DUREE", "pattern": "since this evening"},
    {"label": "DUREE", "pattern": "since today"},
    {"label": "DUREE", "pattern": "since tonight"},
    {"label": "DUREE", "pattern": "since monday"},
    {"label": "DUREE", "pattern": "since tuesday"},
    {"label": "DUREE", "pattern": "since wednesday"},
    {"label": "DUREE", "pattern": "since thursday"},
    {"label": "DUREE", "pattern": "since friday"},
    {"label": "DUREE", "pattern": "since saturday"},
    {"label": "DUREE", "pattern": "since sunday"},
    {"label": "DUREE", "pattern": "last night"},
    {"label": "DUREE", "pattern": "this morning"},
    {"label": "DUREE", "pattern": "this evening"},
    {"label": "DUREE", "pattern": "yesterday"},
    {"label": "DUREE", "pattern": "tonight"},
    {"label": "DUREE", "pattern": "since a few days"},
    {"label": "DUREE", "pattern": "since a few hours"},
    {"label": "DUREE", "pattern": "since a week"},
    {"label": "DUREE", "pattern": "for 2 days"},
    {"label": "DUREE", "pattern": "for 3 days"},
    {"label": "DUREE", "pattern": "for a week"},
    {"label": "DUREE", "pattern": "3 days ago"},
    {"label": "DUREE", "pattern": "2 days ago"},
    {"label": "DUREE", "pattern": "a week ago"},

    # ── BODY_PART ─────────────────────────────────────────────────
    {"label": "BODY_PART", "pattern": "wing"},
    {"label": "BODY_PART", "pattern": "wings"},
    {"label": "BODY_PART", "pattern": "beak"},
    {"label": "BODY_PART", "pattern": "feather"},
    {"label": "BODY_PART", "pattern": "feathers"},
    {"label": "BODY_PART", "pattern": "claw"},
    {"label": "BODY_PART", "pattern": "claws"},
    {"label": "BODY_PART", "pattern": "hind leg"},
    {"label": "BODY_PART", "pattern": "front leg"},
    {"label": "BODY_PART", "pattern": "back leg"},
    {"label": "BODY_PART", "pattern": "lymph node"},
    {"label": "BODY_PART", "pattern": "lymph nodes"},
    {"label": "BODY_PART", "pattern": "eyelid"},
    {"label": "BODY_PART", "pattern": "third eyelid"},
]

ruler.add_patterns(patterns)
print(f"EntityRuler : {len(patterns)} patterns ajoutes")

output_path = Path("models_v2/ner_model_hybrid")
nlp.to_disk(str(output_path))
print(f"Modele hybride sauvegarde : {output_path}")